from controllers.home import Handle_home
from controllers.signup import Handle_signup
from controllers.signin import Handle_signin
from controllers.create_listing import Handle_add_product
from controllers.bidding import Handle_bidding
from controllers.my_bid import Handle_my_bid
from controllers.profile import Handle_profile
from controllers.delete_product import Handle_delete_product
from controllers.update import Handle_update